services:
  mpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-server
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - TRANSPORT=sse
      - LOCAL_VISIO_SERVICE=http://host.docker.internal:8051
    restart: unless-stopped
    networks:
      - mpc-network

# Optional: Only run this if you want the Visio service in a container
# Note: This requires Windows containers and may have limitations
# For most users, running the Visio service directly on the host is recommended
visio-service:
  build:
    context: .
    dockerfile: Dockerfile.visio
  container_name: visio-service
  ports:
    - "8051:8051"
  restart: unless-stopped
  networks:
    - mpc-network
  volumes:
    - ./examples:/app/examples

networks:
  mpc-network:
    driver: bridge 