version: '3.8'

services:
  mpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-server
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - TRANSPORT=sse
      - LOCAL_VISIO_SERVICE=http://host.docker.internal:8051
    restart: unless-stopped
    networks:
      - mpc-network

networks:
  mpc-network:
    driver: bridge 