version: '3.8'

services:
  mpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-server
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - TRANSPORT=sse
      - LOCAL_VISIO_SERVICE=http://host.docker.internal:8052
    restart: unless-stopped
    volumes:
      - ./examples:/app/examples:ro
    networks:
      - mpc-network

  # Note: Visio service requires Windows with Visio installed
  # Uncomment this section if you have Docker Windows containers enabled
  # and Microsoft Visio installed
  #visio-service:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.visio
  #  container_name: visio-service
  #  ports:
  #    - "8051:8051"
  #  environment:
  #    - VISIO_SERVICE_HOST=0.0.0.0
  #    - VISIO_SERVICE_PORT=8051
  #  restart: unless-stopped
  #  volumes:
  #    - ./examples:/app/examples
  #  networks:
  #    - mpc-network

networks:
  mpc-network:
    driver: bridge 